name: dartastic_opentelemetry
description: Dartastic.io's OpenTelemetry SDK for Dart
version: 0.9.3
repository: https://github.com/MindfulSoftwareLLC/dartastic_opentelemetry.git
homepage: https://dartastic.io

environment:
  sdk: ^3.0.0

dependencies:
  dartastic_opentelemetry_api:
    git:
      url: git@github.com:yuzurihaaa/dartastic_opentelemetry_api.git
      ref: cfdeadefc36e3e6643b547abc16a653e7f34b4f7
  fixnum: ^1.1.1
  grpc: ^4.1.0
  http: ^1.5.0
  meta: ^1.16.0
  protobuf: ^4.2.0
  synchronized: ^3.4.0
  web: ^1.1.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  build_runner: ^2.8.0
  lints: ^6.0.0
  mockito: ^5.4.4
  protoc_plugin: ^22.5.0
  test: ^1.26.3

# Script commands
scripts:
  test: dart test
  coverage: ./tools/coverage.sh
  coverage_unit_only: dart test --tags=unit --coverage=coverage
